services:
  blazor-client:
    build:
      context: .
      dockerfile: ./docker/GATEWAY_Launcher/Dockerfile
    image: robocross/gateway-blazor:release
    container_name: blazor-client
    ports:
      - "5001:5001"
    environment:
      # Development:開発設定 appsettings.Development.json
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServer__Address=http://grpc-server:5000
      - Logging__FilePath=/app/logs/launcher/launcher.log
    depends_on:
      - grpc-server
    networks:
      - grpc-network
    restart: unless-stopped
    volumes:
      - ./logs/launcher:/app/logs/launcher

  grpc-server:
    build:
      context: .
      dockerfile: ./docker/GATEWAY_Core/Dockerfile
    image: robocross/gateway-core:release
    container_name: grpc-server
    ports:
      - "5000:5000"
    environment:
      # Development:開発設定 appsettings.Development.json
      - ASPNETCORE_ENVIRONMENT=Development
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
      - Logging__FilePath=/app/logs/core/grpc-server.log
    networks:
      - grpc-network
    restart: unless-stopped
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /etc/machine-id:/etc/machine-id:ro
      - ./logs/core:/app/logs/core
      - ./config:/root/.GATEWAY_Core/Configs/user
      - ./mnt:/app/mnt

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - blazor-client
      - grpc-server
    networks:
      - grpc-network
    restart: unless-stopped

networks:
  grpc-network:
    driver: bridge